name: wahgs2026
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - flopy
  - jupyterlab
  - scipy
  - geopandas
  - rasterio
  - xarray
  - rioxarray
  - netcdf4
  - contextily
  - git
